title: Just the Docs Template
description: A starter template for a Jekyll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: https://mrandrewandrade.github.io/TER/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

markdown: kramdown
kramdown:
  math_engine: mathjax
includes:
  mathjax: mathjax.html
